language: csharp
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11
    - os: windows
branches:
  only:
    - master
    - develop
install:
  - dotnet tool install -g Cake.Tool
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
dotnet: 2.1.502
script:
  - dotnet cake --target=testing