version: '3'
services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - net
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    links:
      - dev
    depends_on:
      - dev
    ports:
      - 80:80
    networks:
      - net
        
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: epicdata
      POSTGRES_USER: postgres
    networks:
      - net
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net
networks:
  net:
    driver: bridge
