version: '3'
services:

  dev:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__default=Database=postgres;Username=postgres;Password=123;Host=db
      - AppSettings__secret=development-secret
    networks:
      - net
  
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    networks:
      - net
        
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    networks:
      - net
        
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mcode.net"
      PGADMIN_DEFAULT_PASSWORD: "123"
    networks:
      - net

networks:
  net:
    driver: bridge
