version: '3'
services:

  dev:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - net
  
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - dev
    ports:
      - 80:80
    networks:
      - net
        
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: epicdata
      POSTGRES_USER: postgres
    networks:
      - net
        
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mcode.net"
      PGADMIN_DEFAULT_PASSWORD: "123"
    depends_on:
      - db
    networks:
      - net

networks:
  net:
    driver: bridge
