apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: interview
build:
  artifacts:

  - image: roygi-docker-mdocker.bintray.io/docs
    context: docs
    docker:
      dockerfile: deploy/Dockerfile

  - image: roygi-docker-mdocker.bintray.io/api
    context: csharp
    docker:
      dockerfile: deploy/api/Dockerfile

  - image: roygi-docker-mdocker.bintray.io/web
    context: ui/web
    docker:
      dockerfile: deploy/Dockerfile

deploy:
  kubectl:
    manifests:
     - k8s/issuer.yml
     - k8s/ingress.yml
     - k8s/api.yml
     - k8s/web.yml
     - k8s/docs.yml
     - k8s/secret.yml
