apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: interview
build:
  artifacts:
  - image: roygi-docker-mdocker.bintray.io/docs/docs
    context: docs
    docker:
      dockerfile: deploy/Dockerfile
  - image: roygi-docker-mdocker.bintray.io/api/api
    context: csharp
    docker:
      dockerfile: deploy/Dockerfile
  - image: roygi-docker-mdocker.bintray.io/web/web
    context: ui/web
    docker:
      dockerfile: deploy/Dockerfile
  - image: roygi-docker-mdocker.bintray.io/dbmigration/dbmigration
    context: data
    docker:
      dockerfile: deploy/Dockerfile
    
deploy:
  kubectl:
    manifests:
    - kubernetes/api.yml
    - kubernetes/dbmigration.yml
    - kubernetes/docs.yml
    - kubernetes/ingress.yml
    - kubernetes/issuer.yml
    - kubernetes/redis.yml
    - kubernetes/web.yml
  
