version: 2.1
orbs:
  docker: circleci/docker@0.5.13
  
jobs:
  csharp-build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
	        cd csharp
            dotnet cake
  
  deploy:
    docker:
      - image: gcr.io/k8s-skaffold/skaffold:latest
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            skaffold build

workflows:
  version: 2
  delivery:
    jobs:
      - csharp-build
      - deploy
          requires:
            - csharp-build