version: 2.1
jobs:
  csharp-build:
    docker:
      - image: roygi-docker-mdocker.bintray.io/dotnet/sdk:2.2
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd csharp
            dotnet cake

  deploy:
    docker:
      - image:  roygi-docker-mdocker.bintray.io/skaffold:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: docker login -u roygi -p ${APIKEY} roygi-docker-mdocker.bintray.io
      - run:
          name: set secret
          command: |
            cd k8s
            echo -n '${DBCONNECTION}' | base64 | sed -i 's/{{DBCONNECTION}}/\1/g' secret.yml
            echo -n '${SECRET}' | base64 | sed -i 's/{{SECRET}}/\1/g' secret.yml
      - run:
          name: set kube config
          command: |
            mkdir ${HOME}/.kube
            cp ./k8s/config.yml ${HOME}/.kube/config
            cd ${HOME}/.kube
            sed -i 's/{{cluster}}/'"${CLUSTER}"'/g' config.yaml
            sed -i 's/{{certificate}}/'"${CERTIFICATE}"'/g' config.yaml
            sed -i 's/{{token}}/'"${TOKEN}"'/g' config.yaml
            sed -i 's/{{server}}/'"${SERVER}"'/g' config.yaml
            sed -i 's/{{user}}/'"${USER}"'/g' config.yaml
            kubectl config use-context ${CLUSTER}
      - run:
          name: skaffold deploy
          command: |
            skaffold run

workflows:
  version: 2
  delivery:
    jobs:
      - csharp-build
      - deploy:
          requires:
            - csharp-build