version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            export CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK="true"
            dotnet tool install -g Cake.Tool
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=compile
  
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            export CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK="true"
            dotnet tool install -g Cake.Tool
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=test

  quality:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            export CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK="true"
            dotnet tool install -g nbgv
            dotnet tool install -g Cake.Tool
            dotnet tool install -g dotnet-sonarscanner
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=test
  
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            export CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK="true"
            dotnet tool install -g nbgv
            dotnet tool install -g Cake.Tool
            apt install awscli 
            apt install docker.io
            systemctl start docker
            systemctl enable docker
            
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet ccake --target=deploy            
            
workflows:
  version: 2
  delivery:
    jobs:
      - build
      - test:
          requires:
            - build
      - quality:
          requires:
            - test
      - deploy:
          requires:
            - quality