version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.103-sdk-bionic
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install "Cake.tool" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.31.0
      - run:
          name: Install libcurl3 for GitVersion
          command: |
            apt update
            apt install -q -y libcurl3
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake build.cake --bootstrap
            dotnet cake build.cake --pack
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
        - checkout
        - run: echo "A more familiar hi"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test