version: 2.1
jobs:
  
  csharp-build:
    docker:
      - image: roygi-docker-mdocker.bintray.io/dotnet/sdk:2.2
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd csharp
            dotnet cake

  deploy:
    docker:
      - image:  roygi-docker-mdocker.bintray.io/skaffold:latest
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: docker login -u roygi -p $APIKEY roygi-docker-mdocker.bintray.io
      - run:
          name: set secret
          command: |
            cd k8s
            export DB=$(echo $DBCONNECTION | base64 -w 0)
            export KEY=$(echo $SECRET | base64 -w 0)
            sed -ie "s|{{DBCONNECTION}}|$DB|g" secret.yml
            sed -ie "s|{{SECRET}}|$KEY|g" secret.yml
      - run:
          name: set kube config
          command: |
            
            mkdir ${HOME}/.kube
            cp ./k8s/config.yml $HOME/.kube/config
            cd ${HOME}/.kube
            sed -i "s|{{cluster}}|$CLUSTER|g"         config
            sed -i "s|{{certificate}}|$CERTIFICATE|g" config
            sed -i "s|{{token}}|$TOKEN|g"             config
            sed -i "s|{{server}}|$SERVER|g"           config
            sed -i "s|{{user}}|$USER|g"               config
            cat config
            kubectl config use-context $CLUSTER
      - run:
          name: skaffold deploy
          command: |
            cd /app
            skaffold run

workflows:
  version: 2
  delivery:
    jobs:
      - csharp-build
      - deploy:
          requires:
            - csharp-build