version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool
      - run:
          name: Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=compile
  
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=testing

  quality:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            apt update
            apt -y install default-jdk
            dotnet tool install -g nbgv
            dotnet tool install -g Cake.Tool
            dotnet tool install -g dotnet-sonarscanner
      - run:
          name: Quality
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=quality
  
  deploy:
    executor: aws-cli/default
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-bionic
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install "tools" .NET Core
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g nbgv
            dotnet tool install -g Cake.Tool
      - run:
          name: Install aws tools
          command: |
            apt update
            apt install -y python3-pip
            apt install -y python-pip
            pip install awscli --upgrade --user
            pip3 install awscli --upgrade --user
            export PATH="$PATH/home/ec2-user/.local/bin"
      - aws-cli/setup      
      - run:
          name: Deploy
          command: |
            $(aws ecr get-login --no-include-email)
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=deploy

workflows:
  version: 2
  delivery:
    jobs:
#      - build
#      - test
#      - quality:
#          requires:
#            - build
#            - test
      - deploy
#          requires:
#            - quality