# Default values for server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 407669251131.dkr.ecr.us-east-2.amazonaws.com/server
  tag: 1.1.4-beta
  pullPolicy: IfNotPresent

imagePullSecrets: [aws-ecr]
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30082

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: server.local
      paths: []

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Docker"
  - name: ASPNETCORE_URLS
    value: "http://+:80"
  - name: ConnectionStrings__default
    valueFrom:
      secretKeyRef:
        key: connection
        name: dev-secret
  - name: AppSettings__secret
    valueFrom:
      secretKeyRef:
        key: secret
        name: dev-secret
