kind: Secret
apiVersion: v1
metadata:
  name: m-secret
data:
  connection: {{DB_CONNECTION}}
  secret: {{SECRET}}
  elastic_url: {{ELASTIC_URL}}
  elastic_user: {{ELASTIC_USER}}
  elastic_password: {{ELASTIC_PASSWORD}}
