kind: Secret
apiVersion: v1
metadata:
  name: dev-secret
data:
  connection: SG9zdD1tZGIuY2xjenhpZDRuYnp0LnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTtEYXRhYmFzZT1tZGF0YTtVc2VybmFtZT1tdXNlcjtQYXNzd29yZD1QYXNzd29yZDEyMzQ=
