# Web Services.

apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---

# Web Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-deploy
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      name: web-pod
      labels:
        component: web
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
        - name: web
          image: 407669251131.dkr.ecr.us-east-2.amazonaws.com/web:1.1.2-alpha
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
          env:
            - name: NODE_ENV
              value: production
            - name: VUE_APP_API_URL
              value: http://server:5000/api