#Server Service

apiVersion: v1
kind: Service
metadata:
  name: dev-svc
spec:
  type: NodePort
  selector:
    component: dev
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 30082

---
# Server Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      component: dev
  template:
    metadata:
      labels:
        component: dev
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
        - name: dev-pod
          image: 407669251131.dkr.ecr.us-east-2.amazonaws.com/server:1.1.20-beta-g27e3a02276
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ConnectionStrings__default
              valueFrom:
                secretKeyRef:
                  key: connection
                  name: dev-secret
            - name: AppSettings__secret
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: dev-secret