# Web Services.

apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---

# Web Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-deploy
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      name: web-pod
      labels:
        component: web
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
        - name: web
          image: roygi-docker-mdocker.bintray.io/server/server:latest
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80